### ISSUE TITLE
can not start tool: tidos

### ISSUE THREAD

**Issue by ghost** [prasoonagnihotri/https-github.com-theInfectedDrake-TIDoS-Framework#1]
error throw:

Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 13, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 36, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/tidos/core/Vulnlysis/vuln.py", line 16, in <module>
    from core.Vulnlysis.Oth_Bugs.othbugs import *
  File "/opt/tidos/core/Vulnlysis/Oth_Bugs/othbugs.py", line 21, in <module>
    from sqlbrute import *
  File "modules/0x03-Vulnerability+Analysis/0x03-OtherWebBugs/sqlbrute.py", line 11, in <module>
    import _mysql
  File "build/bdist.linux-x86_64/egg/_mysql.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_mysql.py", line 6, in __bootstrap__
ImportError: libmariadbclient.so.18: cannot open shared object file: No such file or directory

**Comment by VainlyStrain** [comment]
there is a missing dependency in the script

apt install libmariadbclient18 should solve it.

If it then complains about an import, do pip install <nameofimport>
